# .rubocop.yml
AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/queue_schema.rb'
    - "Gemfile"
    - "lib/tasks/*.rake"
    - "bin/*"
    - "config/puma.rb"
    - "config/spring.rb"
    - "config/environments/development.rb"
    - "config/environments/production.rb"
    - "spec/spec_helper.rb"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'config/routes.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/calendars_controller.rb'

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
  AllowedPatterns:
    - '\s*#'

Lint/EmptyBlock:
  Exclude:
    - 'spec/factories/**/*'
